version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123123
    volumes:
      - ./Build/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
