version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123123
    volumes:
      - ./Build/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbit:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
