version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123123
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=321321
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
